Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2022
Var

    p,r2,area :real

Inicio
  escreval("qual o valor do seu raio")
  leia(r2)
  p :=3.14
  area:= p*r2^2
  escreval("o resultado é ", area)


Fimalgoritmo