Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2022
Var
    nome: caracter


Inicio
     escreval ("Qual seu nome de usuario")
     leia (nome)
     escreval ("boa noite " , nome)


Fimalgoritmo